<?php

	// vlozeni CSS
	$this->headLink()->appendStylesheet('/public/css/dialogForms.css', 'screen,projection');
	
	// formular
	if (isset ($this->form)) {
	
		echo "<form action=\"" . $this->form->getAction() . "\" method=\"" . $this->form->getMethod() . "\" class=\"dialog\">
		<table cellspacing=\"6\" class=\"docs\">
		<tr>
			<td>" . $this->form->name . "</td>
		</tr>
		<tr>
			<td>" . $this->form->description . "</td>
		</tr>
		<tr>
			<td class=\"butSubmit\">" . $this->form->callback . $this->form->data . $this->form->butSubmit . "</td>
		</tr>
		</table>
		</form>\n";
	}
	
	$size = ($this->record->size < 513) ? number_format($this->record->size, 0, '.', ' ') . " B" : number_format(($this->record->size / 1024), 0, '.', ' ') . " KB";
	
	echo "<h3>" . __('caption:wiki_other_properties') . "</h3>
	<table cellspacing=\"6\">
	<tr>
		<td>" . __('info:wiki_creation_data') . ":</td>
		<td>" . $this->record->created . "</td>
	</tr>
	<tr>
		<td>" . __('info:wiki_created_by') . ":</td>
		<td>" . $this->record->created_by->first_name . " " . $this->record->created_by->last_name . "</td>
	</tr>
	<tr>
		<td>" . __('info:wiki_last_changed') . ":</td>
		<td>" . $this->record->modified . "</td>
	</tr>
	<tr>
		<td>" . __('info:wiki_last_changed_by') . ":</td>
		<td>" . $this->record->modified_by->first_name . " " . $this->record->modified_by->last_name . "</td>
	</tr>
	<tr>
		<td>" . __('info:wiki_size') . ":</td>
		<td>" . $size . "</td>
	</tr>\n";

	if (!is_null($this->record->node_info->width)) {
		
		echo "<tr>
			<td>" . __('info:wiki_file_type') . ":</td>
			<td>" . __('info:wiki_image') . " " . $this->record->path_info->extension . "</td>
		</tr>
		<tr>
			<td>" . __('info:wiki_image_size') . ":</td>
			<td>" . $this->record->node_info->width . " x " . $this->record->node_info->height . "</td>
		</tr>\n";
	}
	else {
		
		echo "<tr>
			<td>" . __('info:wiki_file_type') . ":</td>
			<td>" . __('info:wiki_document') . " " . $this->record->node_info->path_info['extension'] . "</td>
		</tr>\n";
	}

	echo "</table>\n";
	