<?php

namespace App\Domain\Payloads;

use App\Base\Domain\Payloads\BasePayload;
use App\Domain\Entities\File;
use App\Exceptions\InvalidArgumentException;


class DownloadPayload extends BasePayload
{

    /**
     * @param File|null $data
     * @throws InvalidArgumentException
     */
    public function __construct($data = null)
    {
        if ($data) {
            $this->setData($data);
        }

        parent::__construct($data);
    }


    /**
     * @return File
     */
    public function getData()
    {
        return $this->data;
    }


    /**
     * @param $data
     * @return BasePayload
     * @throws InvalidArgumentException
     */
    public function setData($data)
    {
        if (!$data instanceof File) {
            throw new InvalidArgumentException('Invalid data source for download payload.');
        }

        return parent::setData($data); // TODO: Change the autogenerated stub
    }

}
